export default {
  text: {
    fontSize: {
      XS: 13,
      S: 15,
      M: 17,
      L: 20,
      XL: 25,
      XXL: 35,
      XXXL: 45,
    },
    letterSpacing: {
      XS: 0,
      S: 1,
      M: 2,
      L: 3,
      XL: 4,
    },
    fontFamily: {
      REGULAR: 'MontserratRegular',
      MEDIUM: 'MontserratMedium',
      BOLD: 'MontserratBold',
    },
  },
  borderRadius: {
    XS: 5,
    S: 8,
    M: 10,
    L: 15,
    XL: 20,
    XXL: 30,
    XXXL: 40,
  },
  colors: {
    white: '#FFFFFF',
    veryLightGrey: '#F9FAFC',
    lightGrey: '#F1F1F1',
    grey: '#8D8A9B',
    darkGrey: '#646567',
    black: '#000000',
    success: '#00C851',
    info: '#35C4FC',
    warning: '#ffbb33',
    error: '#FF3548',
    theme_black_pink: {
      primary: '#000000',
      secondary: '#0057FF',
      // secondary: '#fc00ff',
    },
    theme_sweet_morning: {
      primary: '#ff5f6d',
      secondary: '#ffc371',
    },
    theme_back_to_earth: {
      primary: '#00C9FF',
      secondary: '#92FE9D',
    },
    theme_timber: {
      primary: '#fc00ff',
      secondary: '#00dbde',
    },
    theme_sublime_light: {
      primary: '#FC5C7D',
      secondary: '#6A82FB',
    },
    theme_mini: {
      primary: '#30E8BF',
      secondary: '#FF8235',
    },
    theme_ibiza_sunset: {
      primary: '#ee0979',
      secondary: '#ff6a00',
    },
    theme_sound_cloud: {
      primary: '#f83600',
      secondary: '#fe8c00',
    },
    theme_morpheus_den: {
      primary: '#6456f6',
      secondary: '#30cfd0',
    },
    theme_young_grass: {
      primary: '#00e3ae',
      secondary: '#9be15d',
    },
    theme_melon: {
      primary: '#FA2A4C',
      secondary: '#00e3ae',
    },
    theme_superman: {
      primary: '#0057FF',
      secondary: '#FF3E4F',
    },
    theme_pink: {
      primary: '#FA2A4C',
      primaryDark: '#8e002f',
      primaryLight: '#fd5984',
      secondary: '#FF3E4F',
      secondaryDark: '#af0038',
      secondaryLight: '#ff7d8f',
      ternary: '#F77776',
      ternaryDark: '#c0474a',
      ternaryLight: '#ffa8a5',
    },
    theme_purple: {
      primary: '#AD3DC5',
      primaryDark: '#7a0094',
      primaryLight: '#e270f8',
      secondary: '#DC2C9E',
      secondaryDark: '#a6006f',
      secondaryLight: '#ff68cf',
      ternary: '#F038FF',
      ternaryDark: '#b900cb',
      ternaryLight: '#ff75ff',
    },
    theme_blue: {
      primary: '#192BC2',
      primaryDark: '#000390',
      primaryLight: '#6456f6',
      secondary: '#0057FF',
      secondaryDark: '#002fcb',
      secondaryLight: '#6c83ff',
      ternary: '#4552CB',
      ternaryDark: '#002a99',
      ternaryLight: '#7d7eff',
    },
    theme_green: {
      primary: '#14A095',
      primaryDark: '#007167',
      primaryLight: '#5ad2c5',
      secondary: '#7CCB75',
      secondaryDark: '#4b9a48',
      secondaryLight: '#aeffa5',
      ternary: '#4DB884',
      ternaryDark: '#078757',
      ternaryLight: '#81ebb4',
    },
    theme_pastel: {
      primary: '#CE96FB',
      primaryDark: '#9b67c8',
      primaryLight: '#ffc7ff',
      secondary: '#FF8FCF',
      secondaryDark: '#ca5e9e',
      secondaryLight: '#ffc1ff',
      ternary: '#00C2BA',
      ternaryDark: '#00918a',
      ternaryLight: '#60f5ec',
    },
    theme_sunset: {
      primary: '#c70039',
      primaryDark: '#8d0013',
      primaryLight: '#ff4f63',
      secondary: '#900c3f',
      secondaryDark: '#5c0019',
      secondaryLight: '#c54769',
      ternary: '#ff5733',
      ternaryDark: '#c41c04',
      ternaryLight: '#ff8a5f',
    },
  },
};
