export const CATEGORIES = {
  NAILS: 'NAILS',
  HAIR: 'HAIR',
  MAKE_UP: 'MAKE_UP',
  WAXING: 'WAXING',
  EYELASHES: 'EYELASHES',
  EYEBROWS: 'EYEBROWS',
  FACIALS: 'FACIALS',
  MASSAGE: 'MASSAGE',
  OTHER: 'OTHER',
};
